# Configuración básica
title: yerayleon:~$
description: Portfolio personal y documentación

# Activar el tema de b2a3e8
remote_theme: b2a3e8/jekyll-theme-console

# Opciones específicas del tema Console
style: dark # Puedes cambiarlo a 'light' si prefieres fondo claro

# Barra de navegación superior
header_pages:
  - index.md
