title: yerayleon:~$
description: Portfolio personal y documentación
remote_theme: b2a3e8/jekyll-theme-console

# --- APARIENCIA ---
style: dark
listen_for_clients_preferred_style: true
disable_google_fonts: true

# Pie de página (soporta HTML)
footer: '&copy; 2026 Yeray Leon | <a href="https://github.com/SamuraySanta ">GitHub</a> | <a href="https://linkedin.com/in/yeray-leon-belmonte">LinkedIn</a>'

# --- OPTIMIZACIÓN ---
# Corregido: La sintaxis YAML requiere salto de línea y sangría aquí
sass:
  style: compressed

# --- PLUGINS (Recomendados por el tema) ---
plugins:
  - jekyll-seo-tag
  - jekyll-feed # (Opcional) Útil si vas a tener una sección de blog/notas

# --- NAVEGACIÓN ---
header_pages:
  - index.md
  - proyectos.md
  - about.md
  - contact.md
